site_name: MeshyDB
    
theme: readthedocs
    
nav:
    - Introduction: index.md
    - Test: test.md

extra_css: 
    - css/syntaxhighlight.css
    - css/tabs.css

extra_javascript: 
    - scripts/tabs.js
