site_name: MeshyDB
    
theme: readthedocs
    
nav:
    - Introduction: index.md
    - Test: test.md

extra_css: 
    - css/syntaxhighlight.css
    
extra_javascript:
    - https://cdn.jsdelivr.net/npm/docsify@4
